AWSTemplateFormatVersion: '2010-09-09'
Description: Template for spinning up a Public subnet and a private subnet with NAT Gateway
Parameters:
  ServiceName:
    Description: Service name
    Type: String
    Default: 'MyService'
Resources:
  VPC:
    Type: 'AWS::EC2::VPC'
    Properties:
      CidrBlock: '10.0.0.0/16'
      EnableDnsSupport: true
      EnableDnsHostnames: true
      InstanceTenancy: default
      Tags:
      - Key: Name
        Value:
          Fn::Join:
          - '-'
          - - Ref: ServiceName
            - 'vpc'
            - Ref: AWS::StackName